# Generated by Django 5.2.4 on 2025-07-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='last_day_progress',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='score',
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('head', 'Head'), ('admin', 'Admin')], default='employee', max_length=20),
        ),
    ]
