# Generated by Django 5.2.4 on 2025-07-21 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='progress',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
